### ISSUE TITLE
Cannot read property 'addMethod' of undefined

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/edd-favorites#1]
Javascript throws error `Cannot read property 'addMethod' of undefined` when EDD Favorites is active

Probably jQuery Validation is not loaded well

Tested with custom and vendd theme both

```javascript
                // multi email validation
		jQuery.validator.addMethod(
		    "multiemail",
		    function (value, element) {
		        var email = value.split(/[;,]+/); // split element by , and ;
		        valid = true;
		        for (var i in email) {
		            value = email[i];
		            valid = valid && jQuery.validator.methods.email.call(this, $.trim(value), element);
		        }
		        return valid;
		    },
		    jQuery.validator.messages.multiemail
		);
```

**Comment by sumobi** [comment]
@rubengc Can you outline some steps to reproduce? I'm not seeing any JS errors with Vendd and the latest versions of EDD Wish Lists and favorites. What versions are you using?

**Comment by rubengc** [comment]
Their versions are:
EDD Favorites: 1.0.7
EDD Wish Lists: 1.1.2

**Comment by sumobi** [comment]
@rubengc what page do you see the JS error on? Can you reproduce the JS error with only those plugins (+ EDD) active?

**Comment by rubengc** [comment]
It is so extrange, I disabled all extensions and enable again and now works included with a custom theme :/

**Comment by sumobi** [comment]
Ok great. If it pops up again feel free to re-open this issue.

**Comment by rubengc** [comment]
It is something really really strange

Sometimes displays again the error and if I reload the page again the error disappears

Tested with vendd and custom theme
Chrome has cache disabled when dev tools are open

**Comment by rubengc** [comment]
I have inspected the header and footer and sometimes jquery validation is not added :disappointed:

**Comment by sumobi** [comment]
Happy to continue testing. As per https://github.com/easydigitaldownloads/edd-favorites/issues/1#issuecomment-217758831 and https://github.com/easydigitaldownloads/edd-favorites/issues/1#issuecomment-218307382, can you provide some exact steps to reproduce, including which pages you see the issue on?

**Comment by rubengc** [comment]
Finally I found what happen

Problem comes from Unyson framework (only throws this error on pages where I use it)

But this leads to an even greater problem, I have a home page that's using this extension to show products carousels (owl carousel) ,testimonials, etc etc

as EDD Favorites throws this error, all components from javascript stop working

Where can I want to solve this?

**Comment by rubengc** [comment]
I close this because issue is solved

Unyson framework builds their own cache of public resources, when this cache being updated again everything works

Thanks @sumobi for the help
